spring:
  data:
    elasticsearch:
      cluster-name=my-application: my-es
      cluster-nodes: 127.0.0.1:9300

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

    druid:
      filters: stat,slf4j
      # 启动监控页面，考虑安全问题，默认是关闭的，按需开启。http://127.0.0.1:8080/druid
      stat-view-servlet:
        enabled: true
      web-stat-filter:
        enabled: true
      filter:
        stat:
          enabled: true
        # 打印可执行SQL
        slf4j:
          enabled: true
          statement-close-after-log-enabled: false

  rabbitmq:
    # 开启生产者确认
    publisher-confirm-type: correlated

logging:
  level:
    druid:
      sql:
        Statement: DEBUG
